[[main]]
  name = "Writeups"
  pageRef = "writeups"
  weight = 10

[[main]]
  name = "Notes"
  pageRef = "notes"
  weight = 20

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 30

[[main]]
  name = "About"
  pageRef = "/es/about/"
  weight = 40