[[main]]
  name = "Writeups"
  pageRef = "writeups"
  weight = 10

[[main]]
  name = "Apuntes"
  pageRef = "notes"
  weight = 20

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 30

[[main]]
  name = "Sobre mí"
  pageRef = "about"
  weight = 40